/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import view.prChangeP;
import view.prLoan;
import view.prNewEmployee;
import view.prSAreas;
import view.prSMSalary;
import view.prSSettings;
import view.prSUser;
import view.prSalary;
import view.prSalaryHistory;

/**
 *
 * @author ACER
 */
public class prMainMenu extends javax.swing.JFrame {
    
    javax.swing.Timer mytime;
    SimpleDateFormat sdf;

    /**
     * Creates new form prMainMenu
     */
    public prMainMenu() {
        initComponents();
        setIconImage((new ImageIcon(getClass().getResource("/Pictures/wallet_64.png")).getImage()));
        setClock();
    }
    
    public void setClock() {
        try {
            sdf = new SimpleDateFormat("hh:mm:ss a");
            mytime = new javax.swing.Timer(1000, new ActionListener() {

                public void actionPerformed(ActionEvent e) {
                    Date d = new Date();
                    txtTime.setText(sdf.format(d));
                }
            });
            mytime.start();
        } catch (Exception e) {
        }
        try {
            Date d = new Date();
            txtDate.setText(d + "");
            SimpleDateFormat sf = new SimpleDateFormat("yyyy MMMMM dd");
            String sdf = sf.format(d);
            txtDate.setText(sdf);
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Employee = new javax.swing.JButton();
        Salary = new javax.swing.JButton();
        PaySheet = new javax.swing.JButton();
        SystemSettings = new javax.swing.JButton();
        txtSUser = new javax.swing.JLabel();
        txtDate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        UserSettings = new javax.swing.JButton();
        txtTime = new javax.swing.JLabel();
        Loan = new javax.swing.JButton();
        Areas = new javax.swing.JButton();
        Summary = new javax.swing.JButton();
        change_pw = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard  - Payroll System");
        setResizable(false);

        Employee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Employee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/people-04.png"))); // NOI18N
        Employee.setText("Employee");
        Employee.setBorderPainted(false);
        Employee.setContentAreaFilled(false);
        Employee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Employee.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Employee.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeActionPerformed(evt);
            }
        });

        Salary.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Salary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/salary.png"))); // NOI18N
        Salary.setText("Salary");
        Salary.setBorderPainted(false);
        Salary.setContentAreaFilled(false);
        Salary.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salary.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Salary.setMaximumSize(new java.awt.Dimension(183, 177));
        Salary.setMinimumSize(new java.awt.Dimension(183, 177));
        Salary.setPreferredSize(new java.awt.Dimension(183, 177));
        Salary.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Salary.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalaryActionPerformed(evt);
            }
        });

        PaySheet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PaySheet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/invoice-01.png"))); // NOI18N
        PaySheet.setText("Pay Slip");
        PaySheet.setBorderPainted(false);
        PaySheet.setContentAreaFilled(false);
        PaySheet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PaySheet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PaySheet.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        PaySheet.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        PaySheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaySheetActionPerformed(evt);
            }
        });

        SystemSettings.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SystemSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Setings.png"))); // NOI18N
        SystemSettings.setText("System Settings");
        SystemSettings.setBorderPainted(false);
        SystemSettings.setContentAreaFilled(false);
        SystemSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SystemSettings.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SystemSettings.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SystemSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SystemSettingsActionPerformed(evt);
            }
        });

        txtSUser.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtSUser.setForeground(new java.awt.Color(0, 0, 255));
        txtSUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtSUser.setBorder(new javax.swing.border.MatteBorder(null));

        txtDate.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtDate.setForeground(new java.awt.Color(0, 0, 255));
        txtDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDate.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Current User :");

        UserSettings.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        UserSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/UserSettings.png"))); // NOI18N
        UserSettings.setText("User Settings");
        UserSettings.setBorderPainted(false);
        UserSettings.setContentAreaFilled(false);
        UserSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UserSettings.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        UserSettings.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        UserSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserSettingsActionPerformed(evt);
            }
        });

        txtTime.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtTime.setForeground(new java.awt.Color(0, 0, 255));
        txtTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTime.setBorder(new javax.swing.border.MatteBorder(null));

        Loan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Loan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Loan.png"))); // NOI18N
        Loan.setText("Loan");
        Loan.setBorderPainted(false);
        Loan.setContentAreaFilled(false);
        Loan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Loan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Loan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Loan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoanActionPerformed(evt);
            }
        });

        Areas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Areas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Arreas.png"))); // NOI18N
        Areas.setText("Areas");
        Areas.setBorderPainted(false);
        Areas.setContentAreaFilled(false);
        Areas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Areas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Areas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Areas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreasActionPerformed(evt);
            }
        });

        Summary.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Summary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Summary.png"))); // NOI18N
        Summary.setText("Summary");
        Summary.setBorderPainted(false);
        Summary.setContentAreaFilled(false);
        Summary.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Summary.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Summary.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Summary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SummaryActionPerformed(evt);
            }
        });

        change_pw.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        change_pw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/changepw_icon.png"))); // NOI18N
        change_pw.setText("Change Password");
        change_pw.setBorderPainted(false);
        change_pw.setContentAreaFilled(false);
        change_pw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        change_pw.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        change_pw.setMargin(new java.awt.Insets(12, 14, 2, 14));
        change_pw.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        change_pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_pwActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("this enterprise level java application develop by our team.");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSUser, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(UserSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Loan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Employee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Areas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(change_pw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Salary, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(SystemSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Summary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(PaySheet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Salary, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(Employee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PaySheet, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Loan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Summary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Areas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SystemSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(change_pw, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(692, 711));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeActionPerformed

        try {
            prNewEmployee e = new prNewEmployee();
            e.setVisible(true);
//            gmGRN.txtCSUser.setText(txtCUser.getText());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_EmployeeActionPerformed

    private void SalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalaryActionPerformed

        try {
            prSalary s = new prSalary();
            s.setVisible(true);
            prSalary.txtCUser.setText(txtSUser.getText());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_SalaryActionPerformed

    private void PaySheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaySheetActionPerformed

        try {
            prSalaryHistory sh = new prSalaryHistory();
            sh.setVisible(true);
//            gmGRN.txtCSUser.setText(txtCUser.getText());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_PaySheetActionPerformed

    private void UserSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserSettingsActionPerformed

        try {
            prSUser su = new prSUser();
            su.setVisible(true);
//            gmGRN.txtCSUser.setText(txtCUser.getText());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_UserSettingsActionPerformed

    private void SystemSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SystemSettingsActionPerformed

        try {
            prSSettings ss = new prSSettings();
            ss.setVisible(true);
//            gmGRN.txtCSUser.setText(txtCUser.getText());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_SystemSettingsActionPerformed

    private void SummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SummaryActionPerformed

        try {
            prSMSalary sm = new prSMSalary();
            sm.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_SummaryActionPerformed

    private void LoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoanActionPerformed

        try {
            prLoan l = new prLoan();
            l.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_LoanActionPerformed

    private void AreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreasActionPerformed

        try {
            prSAreas sA = new prSAreas();
            sA.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_AreasActionPerformed

    private void change_pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_pwActionPerformed
   try {
            prChangeP cP = new prChangeP();
            cP.setVisible(true);
            prChangeP.txtUName.setText(txtSUser.getText());
        } catch (Exception e) {
            e.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_change_pwActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Areas;
    private javax.swing.JButton Employee;
    private javax.swing.JButton Loan;
    private javax.swing.JButton PaySheet;
    private javax.swing.JButton Salary;
    private javax.swing.JButton Summary;
    public static javax.swing.JButton SystemSettings;
    public static javax.swing.JButton UserSettings;
    public static javax.swing.JButton change_pw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtDate;
    public static javax.swing.JLabel txtSUser;
    private javax.swing.JLabel txtTime;
    // End of variables declaration//GEN-END:variables
}
